### ISSUE TITLE
Missing matplotlib requirement for FS_1_MVP_Analysis_Prototype_101.ipynb

### ISSUE THREAD

**Issue by schnaitter** [dh-network/quadriga#1]
I used the following commands to install the requirements:
```bash
$ conda create --name quadriga-text python=3.12
$ conda activate quadriga-text
$ pip install -r requirements.txt
```

This does not seem to install `matplotlib` which is used in `WordSearchEngine.search_and_plot()`.

https://github.com/dh-network/quadriga/blob/fdd4cf96be80c69513b051d5abbea226602b6059/word_search/FS_1_MVP_Analysis_Prototype_101.ipynb#L121-L126

Using `pip install matplotlib` in the environment fixed the issue.

**Comment by hsluytergaethje** [comment]
Matplotlib was added to the requirements.txt in this commit d3fbb3771a7f823cf82f29fda7be8132ff0a8328 which solves the issue.
