### ISSUE TITLE
Clone Issue: Invalid Path Errors in data_aux Directory

### ISSUE THREAD

**Issue by lam1aa** [dh-network/quadriga#19]
Error Details: While cloning the repository to a local machine, some files in the `data_aux` directory are showing **invalid path** errors.
OS: **Windows**
Reproduction Steps:
Clone the repository to a Windows machine using **GitHub Desktop** or **Git Bash**.
The cloning process fails with errors for specific files.
I’ve attached **screenshots** of the errors for reference.
![Screenshot 2024-12-05 224551](https://github.com/user-attachments/assets/b796e55f-19cf-445f-83fa-1bf4b63a942f)
![Screenshot 2024-12-05 224620](https://github.com/user-attachments/assets/59774115-e922-4a2b-b859-73add94575f7)

**Comment by hsluytergaethje** [comment]
Thanks you for reporting the issue. It seems like in Windows, directories / files may not be named "aux", see here: https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file
I'll rename the directory.
