### ISSUE TITLE
Minor didactic suggestion: Explain file paths in NLP-Enrichment.ipynb

### ISSUE THREAD

**Issue by Philipp-Schneider** [dh-network/quadriga#4]
I would suggest to add or link to a short explanation of how file paths work. Especially the difference between absolute and relative paths is often not clear -- depending on the proficiency level of the user. On the other hand, I think it would be important to understand this to reuse the notebook with other datasets.

**Comment by hsluytergaethje** [comment]
Yes, that makes sense. At the moment, we first mention file paths in the [OCR input notebook](https://github.com/dh-network/quadriga/blob/main/data-input/FS_1_MVP_OCR.ipynb). We could have an admonition-box for this, something like "Mehr zu Dateipfaden" or the like.

**Comment by DanilSko** [comment]
> We could have an admonition-box for this, something like "Mehr zu Dateipfaden" or the like.

I added a 'Was ist ein Dateipfad?' unfoldable explainer. @hsluytergaethje is this close to what you had in mind?
